### ISSUE TITLE
Umbrella doesn't work during Astral Sorcery's solar eclipse

### ISSUE THREAD

**Issue by Aphyxia** [Focamacho/VampiresNeedUmbrellas#3]
Umbrella stops working during the solar eclipse from Astral Sorcery. Shouldn't it be that you don't actually need an umbrella while the solar eclipse is happening? :P
The skill sunscreen prevents sun damage during this period as it should.

MC 1.12.2
astralsorcery-1.12.2-1.10.23
VampiresNeedUmbrellas-1.12.2-1.3
forge 14.23.5.2847

**Comment by focamacho** [comment]
You're not using the latest version of the mod, the latest version has some sunlight detection fixes
https://www.curseforge.com/minecraft/mc-mods/vampires-need-umbrellas/files/2946161

**Comment by Aphyxia** [comment]
Ah, sorry. I somehow saw that it was the latest version. Not sure how I made that mistake.
In all likelihood this is patched then but I don't have the liberty of testing it as I'm playing on a modpack server.

If anyone else has this problem and the newest version doesn't fix it, feel free to reopen the issue.
