### ISSUE TITLE
Crash when putting an umbrella into the Inventory

### ISSUE THREAD

**Issue by Maxi90909** [Focamacho/VampiresNeedUmbrellas#33]
Hi, I added the mod to my mod list yesterday. I crafted an umbrealla however my game crashes when I do that. Basically I craft the umbrella and I put it in my inventory and my game crashes. I am not a vampire (wanted to become one) and I also have the curio datapack for the umbrella installed. The crash report says something about that. Here is my crash report:
https://pastebin.com/AhpQDEbU

**Comment by Maxi90909** [comment]
I now had to remove the mod, since it crashed my world everytime I started it, even after I removed the curio datapack.

**Comment by focamacho** [comment]
Hey! Seems like you are using an outdated version of Curios, try updating to the latest one.

**Comment by Maxi90909** [comment]
I updated Curios and it fixed it.
Most of my mods don‘t get marked with the green point when an update is available. That’s why I didn‘t update. Thank you!

**Comment by focamacho** [comment]
Glad it worked! Have fun playing and thanks for using my mod!
