### ISSUE TITLE
Umbrellas stop working when in water

### ISSUE THREAD

**Issue by rabalais** [Focamacho/VampiresNeedUmbrellas#6]
Standing in water the umbrella will stop working in either hands. 
![image](https://user-images.githubusercontent.com/60150831/105789334-dffabb80-5f47-11eb-8f92-fd74a2ca99b6.png)

It will work for a little while then I assume the durability or something goes down and it then stops working. Tested by jumping in the water with umbrella in either hands and by just standing in one block deep water. 

I saw the boat fix but I was unsure if it applied to what I was experiencing as well so I went ahead and made and issue. If it does just close the issue. Thanks.

Edit: Modpack is mceternal. Latest version.

**Comment by focamacho** [comment]
Hello, make sure you're using the latest version of the mod, this issue was already fixed.
Last time I checked MC Eternal wasnt using the latest version of this mod.
