### ISSUE TITLE
Umbrellas not protecting from sunlight after using creative umbrella for a while

### ISSUE THREAD

**Issue by ghost** [Focamacho/VampiresNeedUmbrellas#7]

**Comment by focamacho** [comment]
What version are you using?

**Comment by ghost** [comment]
im using version 1.6.2 for mc 1.12.2

**Comment by focamacho** [comment]
Are you sure? The latest version for 1.12.2 is the 1.5 https://www.curseforge.com/minecraft/mc-mods/vampires-need-umbrellas/files/2946161

**Comment by ghost** [comment]
oops version 1.3 not 1.6, confusedit with the vampirism mod

**Comment by ghost** [comment]
Also, the iron umbrella just instant breaks, and the diamond umbrella breaks after 2 damage ticks

**Comment by focamacho** [comment]
Weird, this issue never happened before. Try using the latest version.

**Comment by focamacho** [comment]
Also try to delete your VampiresNeedUmbrellas config file, so it will be created again. Maybe something happened to it.

**Comment by ghost** [comment]
Thanks, gonna give an update tomorrow, becuse its kinda late here and i dont have the time to start mc

**Comment by ghost** [comment]
No, still doesnt work, could there be a conflict with matteroverdrive because you cant get potion effects?`

**Comment by focamacho** [comment]
Maybe. If something is removing the potion effects this issue can happen, cuz this mod uses the sunscreen effect from Vampirism to work.

**Comment by ghost** [comment]
Then it is a problem with being an android, because by default it disables, that you can get any potion effects.
